#!/usr/bin/env bash
# Regenerate scripts/import_parquets_to_sqlite.sql with one CREATE TABLE statement
# per Parquet file found in ./data/*.parquet.
# Usage: ./scripts/generate_import_sql.sh

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
SQL_FILE="scripts/import_parquets_to_sqlite.sql"

cat > "$SQL_FILE" <<'SQL'
-- AUTO-GENERATED by scripts/generate_import_sql.sh
-- Copies every Parquet file in ./data into SQLite tables in bbsim.db using DuckDB.
-- Usage:
--   duckdb -c ".read $SQL_FILE"

INSTALL sqlite;
LOAD sqlite;

ATTACH 'bbsim.db' AS sqlite (TYPE SQLITE);
SQL

echo "-- importing tables" >> "$SQL_FILE"

for parquet in data/*.parquet; do
  base=$(basename "$parquet")
  tbl=${base%.parquet}
  echo "CREATE OR REPLACE TABLE sqlite.${tbl} AS SELECT * FROM read_parquet('${parquet}');" >> "$SQL_FILE"
  echo >> "$SQL_FILE"
done

echo -e "PRAGMA show_tables('sqlite');\n" >> "$SQL_FILE"

printf 'Generated %s with %d tables.\n' "$SQL_FILE" $(ls data/*.parquet | wc -l)
