-- AUTO-GENERATED by scripts/generate_import_sql.sh
-- Copies every Parquet file in ./data into SQLite tables in bbsim.db using DuckDB.
-- Usage:
--   duckdb -c ".read $SQL_FILE"

INSTALL sqlite;
LOAD sqlite;

ATTACH 'bbsim.db' AS sqlite (TYPE SQLITE);
-- importing tables
CREATE OR REPLACE TABLE sqlite.calc_batted_ball_type AS SELECT * FROM read_parquet('data/main_models_calc_batted_ball_type.parquet');

CREATE OR REPLACE TABLE sqlite.calc_fielding_play_agg AS SELECT * FROM read_parquet('data/main_models_calc_fielding_play_agg.parquet');

CREATE OR REPLACE TABLE sqlite.calc_park_factors_advanced AS SELECT * FROM read_parquet('data/main_models_calc_park_factors_advanced.parquet');

CREATE OR REPLACE TABLE sqlite.calc_park_factors_basic AS SELECT * FROM read_parquet('data/main_models_calc_park_factors_basic.parquet');

CREATE OR REPLACE TABLE sqlite.event_base_out_states AS SELECT * FROM read_parquet('data/main_models_event_base_out_states.parquet');

CREATE OR REPLACE TABLE sqlite.event_baserunning_stats AS SELECT * FROM read_parquet('data/main_models_event_baserunning_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_batted_ball_stats AS SELECT * FROM read_parquet('data/main_models_event_batted_ball_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_batting_stats AS SELECT * FROM read_parquet('data/main_models_event_batting_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_count_states AS SELECT * FROM read_parquet('data/main_models_event_count_states.parquet');

CREATE OR REPLACE TABLE sqlite.event_double_plays AS SELECT * FROM read_parquet('data/main_models_event_double_plays.parquet');

CREATE OR REPLACE TABLE sqlite.event_fielders_flat AS SELECT * FROM read_parquet('data/main_models_event_fielders_flat.parquet');

CREATE OR REPLACE TABLE sqlite.event_fielding_stats AS SELECT * FROM read_parquet('data/main_models_event_fielding_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_offense_stats AS SELECT * FROM read_parquet('data/main_models_event_offense_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_personnel_lookup AS SELECT * FROM read_parquet('data/main_models_event_personnel_lookup.parquet');

CREATE OR REPLACE TABLE sqlite.event_pitch_sequence_stats AS SELECT * FROM read_parquet('data/main_models_event_pitch_sequence_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_pitching_flags AS SELECT * FROM read_parquet('data/main_models_event_pitching_flags.parquet');

CREATE OR REPLACE TABLE sqlite.event_pitching_stats AS SELECT * FROM read_parquet('data/main_models_event_pitching_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_player_fielding_stats AS SELECT * FROM read_parquet('data/main_models_event_player_fielding_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_run_assignment_stats AS SELECT * FROM read_parquet('data/main_models_event_run_assignment_stats.parquet');

CREATE OR REPLACE TABLE sqlite.event_score_states AS SELECT * FROM read_parquet('data/main_models_event_score_states.parquet');

CREATE OR REPLACE TABLE sqlite.event_states_batter_pitcher AS SELECT * FROM read_parquet('data/main_models_event_states_batter_pitcher.parquet');

CREATE OR REPLACE TABLE sqlite.event_states_full AS SELECT * FROM read_parquet('data/main_models_event_states_full.parquet');

CREATE OR REPLACE TABLE sqlite.event_transition_values AS SELECT * FROM read_parquet('data/main_models_event_transition_values.parquet');

CREATE OR REPLACE TABLE sqlite.game_forfeits AS SELECT * FROM read_parquet('data/main_models_game_forfeits.parquet');

CREATE OR REPLACE TABLE sqlite.game_line_scores AS SELECT * FROM read_parquet('data/main_models_game_line_scores.parquet');

CREATE OR REPLACE TABLE sqlite.game_results AS SELECT * FROM read_parquet('data/main_models_game_results.parquet');

CREATE OR REPLACE TABLE sqlite.game_scorekeeping AS SELECT * FROM read_parquet('data/main_models_game_scorekeeping.parquet');

CREATE OR REPLACE TABLE sqlite.game_start_info AS SELECT * FROM read_parquet('data/main_models_game_start_info.parquet');

CREATE OR REPLACE TABLE sqlite.game_starting_lineups AS SELECT * FROM read_parquet('data/main_models_game_starting_lineups.parquet');

CREATE OR REPLACE TABLE sqlite.game_suspensions AS SELECT * FROM read_parquet('data/main_models_game_suspensions.parquet');

CREATE OR REPLACE TABLE sqlite.leverage_index AS SELECT * FROM read_parquet('data/main_models_leverage_index.parquet');

CREATE OR REPLACE TABLE sqlite.linear_weights AS SELECT * FROM read_parquet('data/main_models_linear_weights.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_player_career_fielding AS SELECT * FROM read_parquet('data/main_models_metrics_player_career_fielding.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_player_career_offense AS SELECT * FROM read_parquet('data/main_models_metrics_player_career_offense.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_player_career_pitching AS SELECT * FROM read_parquet('data/main_models_metrics_player_career_pitching.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_player_season_league_fielding AS SELECT * FROM read_parquet('data/main_models_metrics_player_season_league_fielding.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_player_season_league_offense AS SELECT * FROM read_parquet('data/main_models_metrics_player_season_league_offense.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_player_season_league_pitching AS SELECT * FROM read_parquet('data/main_models_metrics_player_season_league_pitching.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_team_season_fielding AS SELECT * FROM read_parquet('data/main_models_metrics_team_season_fielding.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_team_season_offense AS SELECT * FROM read_parquet('data/main_models_metrics_team_season_offense.parquet');

CREATE OR REPLACE TABLE sqlite.metrics_team_season_pitching AS SELECT * FROM read_parquet('data/main_models_metrics_team_season_pitching.parquet');

CREATE OR REPLACE TABLE sqlite.ml_event_outcomes AS SELECT * FROM read_parquet('data/main_models_ml_event_outcomes.parquet');

CREATE OR REPLACE TABLE sqlite.ml_features AS SELECT * FROM read_parquet('data/main_models_ml_features.parquet');

CREATE OR REPLACE TABLE sqlite.park_factors AS SELECT * FROM read_parquet('data/main_models_park_factors.parquet');

CREATE OR REPLACE TABLE sqlite.people AS SELECT * FROM read_parquet('data/main_models_people.parquet');

CREATE OR REPLACE TABLE sqlite.personnel_fielding_states AS SELECT * FROM read_parquet('data/main_models_personnel_fielding_states.parquet');

CREATE OR REPLACE TABLE sqlite.personnel_lineup_states AS SELECT * FROM read_parquet('data/main_models_personnel_lineup_states.parquet');

CREATE OR REPLACE TABLE sqlite.player_game_appearances AS SELECT * FROM read_parquet('data/main_models_player_game_appearances.parquet');

CREATE OR REPLACE TABLE sqlite.player_game_offense_stats AS SELECT * FROM read_parquet('data/main_models_player_game_offense_stats.parquet');

CREATE OR REPLACE TABLE sqlite.player_game_pitching_stats AS SELECT * FROM read_parquet('data/main_models_player_game_pitching_stats.parquet');

CREATE OR REPLACE TABLE sqlite.player_position_game_fielding_stats AS SELECT * FROM read_parquet('data/main_models_player_position_game_fielding_stats.parquet');

CREATE OR REPLACE TABLE sqlite.player_position_team_season_fielding_stats AS SELECT * FROM read_parquet('data/main_models_player_position_team_season_fielding_stats.parquet');

CREATE OR REPLACE TABLE sqlite.player_team_season_offense_stats AS SELECT * FROM read_parquet('data/main_models_player_team_season_offense_stats.parquet');

CREATE OR REPLACE TABLE sqlite.player_team_season_pitching_stats AS SELECT * FROM read_parquet('data/main_models_player_team_season_pitching_stats.parquet');

CREATE OR REPLACE TABLE sqlite.run_expectancy_matrix AS SELECT * FROM read_parquet('data/main_models_run_expectancy_matrix.parquet');

CREATE OR REPLACE TABLE sqlite.season_team_coverage AS SELECT * FROM read_parquet('data/main_models_season_team_coverage.parquet');

CREATE OR REPLACE TABLE sqlite.standings AS SELECT * FROM read_parquet('data/main_models_standings.parquet');

CREATE OR REPLACE TABLE sqlite.bio AS SELECT * FROM read_parquet('data/main_models_stg_bio.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_batting_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_batting_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_caught_stealing AS SELECT * FROM read_parquet('data/main_models_stg_box_score_caught_stealing.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_comments AS SELECT * FROM read_parquet('data/main_models_stg_box_score_comments.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_double_plays AS SELECT * FROM read_parquet('data/main_models_stg_box_score_double_plays.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_fielding_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_fielding_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_hit_by_pitches AS SELECT * FROM read_parquet('data/main_models_stg_box_score_hit_by_pitches.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_home_runs AS SELECT * FROM read_parquet('data/main_models_stg_box_score_home_runs.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_line_scores AS SELECT * FROM read_parquet('data/main_models_stg_box_score_line_scores.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_pinch_hitting_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_pinch_hitting_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_pinch_running_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_pinch_running_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_pitching_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_pitching_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_stolen_bases AS SELECT * FROM read_parquet('data/main_models_stg_box_score_stolen_bases.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_team_batting_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_team_batting_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_team_fielding_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_team_fielding_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_team_miscellaneous_lines AS SELECT * FROM read_parquet('data/main_models_stg_box_score_team_miscellaneous_lines.parquet');

CREATE OR REPLACE TABLE sqlite.box_score_triple_plays AS SELECT * FROM read_parquet('data/main_models_stg_box_score_triple_plays.parquet');

CREATE OR REPLACE TABLE sqlite.databank_batting AS SELECT * FROM read_parquet('data/main_models_stg_databank_batting.parquet');

CREATE OR REPLACE TABLE sqlite.databank_fielding_of AS SELECT * FROM read_parquet('data/main_models_stg_databank_fielding_of.parquet');

CREATE OR REPLACE TABLE sqlite.databank_fielding AS SELECT * FROM read_parquet('data/main_models_stg_databank_fielding.parquet');

CREATE OR REPLACE TABLE sqlite.databank_pitching AS SELECT * FROM read_parquet('data/main_models_stg_databank_pitching.parquet');

CREATE OR REPLACE TABLE sqlite.event_audit AS SELECT * FROM read_parquet('data/main_models_stg_event_audit.parquet');

CREATE OR REPLACE TABLE sqlite.event_baserunners AS SELECT * FROM read_parquet('data/main_models_stg_event_baserunners.parquet');

CREATE OR REPLACE TABLE sqlite.event_comments AS SELECT * FROM read_parquet('data/main_models_stg_event_comments.parquet');

CREATE OR REPLACE TABLE sqlite.event_fielding_plays AS SELECT * FROM read_parquet('data/main_models_stg_event_fielding_plays.parquet');

CREATE OR REPLACE TABLE sqlite.event_flags AS SELECT * FROM read_parquet('data/main_models_stg_event_flags.parquet');

CREATE OR REPLACE TABLE sqlite.event_pitch_sequences AS SELECT * FROM read_parquet('data/main_models_stg_event_pitch_sequences.parquet');

CREATE OR REPLACE TABLE sqlite.events AS SELECT * FROM read_parquet('data/main_models_stg_events.parquet');

CREATE OR REPLACE TABLE sqlite.game_earned_runs AS SELECT * FROM read_parquet('data/main_models_stg_game_earned_runs.parquet');

CREATE OR REPLACE TABLE sqlite.game_fielding_appearances AS SELECT * FROM read_parquet('data/main_models_stg_game_fielding_appearances.parquet');

CREATE OR REPLACE TABLE sqlite.game_lineup_appearances AS SELECT * FROM read_parquet('data/main_models_stg_game_lineup_appearances.parquet');

CREATE OR REPLACE TABLE sqlite.gamelog AS SELECT * FROM read_parquet('data/main_models_stg_gamelog.parquet');

CREATE OR REPLACE TABLE sqlite.games AS SELECT * FROM read_parquet('data/main_models_stg_games.parquet');

CREATE OR REPLACE TABLE sqlite.parks AS SELECT * FROM read_parquet('data/main_models_stg_parks.parquet');

CREATE OR REPLACE TABLE sqlite.people AS SELECT * FROM read_parquet('data/main_models_stg_people.parquet');

CREATE OR REPLACE TABLE sqlite.rosters AS SELECT * FROM read_parquet('data/main_models_stg_rosters.parquet');

CREATE OR REPLACE TABLE sqlite.schedule AS SELECT * FROM read_parquet('data/main_models_stg_schedule.parquet');

CREATE OR REPLACE TABLE sqlite.team_game_fielding_stats AS SELECT * FROM read_parquet('data/main_models_team_game_fielding_stats.parquet');

CREATE OR REPLACE TABLE sqlite.team_game_offense_stats AS SELECT * FROM read_parquet('data/main_models_team_game_offense_stats.parquet');

CREATE OR REPLACE TABLE sqlite.team_game_pitching_stats AS SELECT * FROM read_parquet('data/main_models_team_game_pitching_stats.parquet');

CREATE OR REPLACE TABLE sqlite.team_game_results AS SELECT * FROM read_parquet('data/main_models_team_game_results.parquet');

CREATE OR REPLACE TABLE sqlite.team_game_start_info AS SELECT * FROM read_parquet('data/main_models_team_game_start_info.parquet');

CREATE OR REPLACE TABLE sqlite.team_season_fielding_stats AS SELECT * FROM read_parquet('data/main_models_team_season_fielding_stats.parquet');

CREATE OR REPLACE TABLE sqlite.unknown_fielding_play_shares AS SELECT * FROM read_parquet('data/main_models_unknown_fielding_play_shares.parquet');

CREATE OR REPLACE TABLE sqlite.win_expectancy_matrix AS SELECT * FROM read_parquet('data/main_models_win_expectancy_matrix.parquet');

PRAGMA show_tables('sqlite');

